### ISSUE TITLE
what's the meaning of positive class in multi-class task?

### ISSUE THREAD

**Issue by Albert-Ma** [guillaumegenthial/tf_metrics#2]
Hey man, I want to ask the meaning of parameter `pos_indices`.

Which is the `pos_indices` in a multi-class task like 'Image Classify'? You can not say that cat or dog is positive if they have no opposite class, like good and bad.

**Comment by shencunzailaozhang** [comment]
I think the positive class includes entities you want to predict and non-entities like 'O','[CLS]'&'[SEP]' are negative.

**Comment by Albert-Ma** [comment]
@shencunzailaozhang thanks, but I think this script calculates the micro F1 on each entity which is different from the offical  `conlleval` .

**Comment by shencunzailaozhang** [comment]
Yes,I also notice this problem today.The score calculated in this script is based on single char not on the whole entity and many papers adopt the score based on the whole entities.Maybe we can communicate on Wechat if you are Chinese.My Wechat number is shencunzailaozhang
